# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Function\Desktop\GP\gui\patient_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(632, 444)
        Form.setStyleSheet("background-color:#265073;")
        self.EEGpLotwidget = QtWidgets.QWidget(Form)
        self.EEGpLotwidget.setGeometry(QtCore.QRect(140, 70, 352, 322))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.EEGpLotwidget.sizePolicy().hasHeightForWidth())
        self.EEGpLotwidget.setSizePolicy(sizePolicy)
        self.EEGpLotwidget.setMinimumSize(QtCore.QSize(352, 111))
        self.EEGpLotwidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.EEGpLotwidget.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.EEGpLotwidget.setObjectName("EEGpLotwidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 20, 395, 36))
        self.label.setStyleSheet("qproperty-alignment: AlignCenter;\n"
"text-align:center;\n"
"font: 700 20pt; \n"
"color:rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Patient Screen"))
        self.label.setText(_translate("Form", "The session has not started yet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
