# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
import serial
from message_formating import * 
import socket


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(727, 697)
        MainWindow.setStyleSheet("background-color:#265073;\n" "\n" "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.sc_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        self.sc_tab.setFont(font)
        self.sc_tab.setStyleSheet("background-color: rgb(239, 239, 239);\n" "")
        self.sc_tab.setObjectName("sc_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sc_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.sc_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_23 = QtWidgets.QWidget(self.widget_7)
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fes_sc_label = QtWidgets.QLabel(self.widget_23)
        self.fes_sc_label.setStyleSheet(
            "qproperty-alignment: AlignCenter;\n"
            "text-align:center;\n"
            "font: 700 16pt; "
        )
        self.fes_sc_label.setObjectName("fes_sc_label")
        self.verticalLayout_4.addWidget(self.fes_sc_label)
        self.verticalLayout_3.addWidget(self.widget_23)
        self.widget_15 = QtWidgets.QWidget(self.widget_7)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_19 = QtWidgets.QWidget(self.widget_15)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.grasping_fes_sc_label = QtWidgets.QLabel(self.widget_19)
        self.grasping_fes_sc_label.setStyleSheet("font: 600 12pt; ")
        self.grasping_fes_sc_label.setObjectName("grasping_fes_sc_label")
        self.verticalLayout_7.addWidget(self.grasping_fes_sc_label)
        self.horizontalLayout_6.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.widget_15)
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.g_fes_sc_input = QtWidgets.QSpinBox(self.widget_20)
        self.g_fes_sc_input.setMaximum(80)
        self.g_fes_sc_input.setObjectName("g_fes_sc_input")
        self.verticalLayout_14.addWidget(self.g_fes_sc_input)
        self.horizontalLayout_6.addWidget(self.widget_20)
        self.verticalLayout_3.addWidget(self.widget_15)
        self.widget_14 = QtWidgets.QWidget(self.widget_7)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_21 = QtWidgets.QWidget(self.widget_14)
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.g_cv_fes_sc_label = QtWidgets.QLabel(self.widget_21)
        self.g_cv_fes_sc_label.setObjectName("g_cv_fes_sc_label")
        self.verticalLayout_8.addWidget(self.g_cv_fes_sc_label)
        self.horizontalLayout_7.addWidget(self.widget_21)
        self.widget_22 = QtWidgets.QWidget(self.widget_14)
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.g_cv_fes_sc_input = QtWidgets.QTextEdit(self.widget_22)
        self.g_cv_fes_sc_input.setMinimumSize(QtCore.QSize(115, 20))
        self.g_cv_fes_sc_input.setMaximumSize(QtCore.QSize(115, 20))
        self.g_cv_fes_sc_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g_cv_fes_sc_input.setReadOnly(True)
        self.g_cv_fes_sc_input.setObjectName("g_cv_fes_sc_input")
        self.verticalLayout_15.addWidget(self.g_cv_fes_sc_input)
        self.horizontalLayout_7.addWidget(self.widget_22)
        self.verticalLayout_3.addWidget(self.widget_14)
        self.line_2 = QtWidgets.QFrame(self.widget_7)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.widget_12 = QtWidgets.QWidget(self.widget_7)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_17 = QtWidgets.QWidget(self.widget_12)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.releasing_fes_sc_label = QtWidgets.QLabel(self.widget_17)
        self.releasing_fes_sc_label.setStyleSheet("font: 600 12pt; ")
        self.releasing_fes_sc_label.setObjectName("releasing_fes_sc_label")
        self.verticalLayout_10.addWidget(self.releasing_fes_sc_label)
        self.horizontalLayout_10.addWidget(self.widget_17)
        self.widget_18 = QtWidgets.QWidget(self.widget_12)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.r_fes_sc_input = QtWidgets.QSpinBox(self.widget_18)
        self.r_fes_sc_input.setMaximum(80)
        self.r_fes_sc_input.setObjectName("r_fes_sc_input")
        self.verticalLayout_16.addWidget(self.r_fes_sc_input)
        self.horizontalLayout_10.addWidget(self.widget_18)
        self.verticalLayout_3.addWidget(self.widget_12)
        self.widget_11 = QtWidgets.QWidget(self.widget_7)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_27 = QtWidgets.QWidget(self.widget_11)
        self.widget_27.setObjectName("widget_27")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_27)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.r_cv_fes_sc_label = QtWidgets.QLabel(self.widget_27)
        self.r_cv_fes_sc_label.setObjectName("r_cv_fes_sc_label")
        self.verticalLayout_9.addWidget(self.r_cv_fes_sc_label)
        self.horizontalLayout_8.addWidget(self.widget_27)
        self.widget_28 = QtWidgets.QWidget(self.widget_11)
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.r_cv_fes_sc_input = QtWidgets.QTextEdit(self.widget_28)
        self.r_cv_fes_sc_input.setMinimumSize(QtCore.QSize(115, 20))
        self.r_cv_fes_sc_input.setMaximumSize(QtCore.QSize(115, 20))
        self.r_cv_fes_sc_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.r_cv_fes_sc_input.setReadOnly(True)
        self.r_cv_fes_sc_input.setObjectName("r_cv_fes_sc_input")
        self.verticalLayout_17.addWidget(self.r_cv_fes_sc_input)
        self.horizontalLayout_8.addWidget(self.widget_28)
        self.verticalLayout_3.addWidget(self.widget_11)
        self.widget_10 = QtWidgets.QWidget(self.widget_7)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.glove_sc_label = QtWidgets.QLabel(self.widget_10)
        self.glove_sc_label.setStyleSheet(
            "qproperty-alignment: AlignCenter;\n"
            "text-align:center;\n"
            "font: 700 16pt; "
        )
        self.glove_sc_label.setObjectName("glove_sc_label")
        self.verticalLayout_6.addWidget(self.glove_sc_label)
        self.verticalLayout_3.addWidget(self.widget_10)
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_29 = QtWidgets.QWidget(self.widget_9)
        self.widget_29.setObjectName("widget_29")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_29)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.grasping_glove_sc_label = QtWidgets.QLabel(self.widget_29)
        self.grasping_glove_sc_label.setStyleSheet("")
        self.grasping_glove_sc_label.setObjectName("grasping_glove_sc_label")
        self.verticalLayout_11.addWidget(self.grasping_glove_sc_label)
        self.horizontalLayout_11.addWidget(self.widget_29)
        self.widget_30 = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_30.sizePolicy().hasHeightForWidth())
        self.widget_30.setSizePolicy(sizePolicy)
        self.widget_30.setObjectName("widget_30")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_30)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.grasping_glove_sc_value_label = QtWidgets.QLabel(self.widget_30)
        self.grasping_glove_sc_value_label.setObjectName(
            "grasping_glove_sc_value_label"
        )
        self.verticalLayout_18.addWidget(self.grasping_glove_sc_value_label)
        self.horizontalLayout_11.addWidget(self.widget_30)
        self.verticalLayout_3.addWidget(self.widget_9)
        self.widget_13 = QtWidgets.QWidget(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_16 = QtWidgets.QWidget(self.widget_13)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.releasing_glove_sc_label = QtWidgets.QLabel(self.widget_16)
        self.releasing_glove_sc_label.setObjectName("releasing_glove_sc_label")
        self.verticalLayout_12.addWidget(self.releasing_glove_sc_label)
        self.horizontalLayout_5.addWidget(self.widget_16)
        self.widget_26 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_26.sizePolicy().hasHeightForWidth())
        self.widget_26.setSizePolicy(sizePolicy)
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.releasing_glove_sc_value_label = QtWidgets.QLabel(self.widget_26)
        self.releasing_glove_sc_value_label.setObjectName(
            "releasing_glove_sc_value_label"
        )
        self.verticalLayout_19.addWidget(self.releasing_glove_sc_value_label)
        self.horizontalLayout_5.addWidget(self.widget_26)
        self.verticalLayout_3.addWidget(self.widget_13)
        self.horizontalLayout_3.addWidget(self.widget_7)
        self.line = QtWidgets.QFrame(self.widget_5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_25 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_25.sizePolicy().hasHeightForWidth())
        self.widget_25.setSizePolicy(sizePolicy)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.instructions_sc_label = QtWidgets.QLabel(self.widget_25)
        self.instructions_sc_label.setStyleSheet(
            "qproperty-alignment: AlignCenter;\n"
            "text-align:center;\n"
            "font: 700 16pt; "
        )
        self.instructions_sc_label.setObjectName("instructions_sc_label")
        self.verticalLayout_13.addWidget(self.instructions_sc_label)
        self.verticalLayout_5.addWidget(self.widget_25)
        self.widget_24 = QtWidgets.QWidget(self.widget_8)
        self.widget_24.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.widget_24.sizePolicy().hasHeightForWidth())
        self.widget_24.setSizePolicy(sizePolicy)
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.instructions_input = QtWidgets.QTextEdit(self.widget_24)
        self.instructions_input.setReadOnly(True)
        self.instructions_input.setObjectName("instructions_input")
        self.horizontalLayout_9.addWidget(self.instructions_input)
        self.verticalLayout_5.addWidget(self.widget_24)
        self.horizontalLayout_3.addWidget(self.widget_8)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.sc_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem)
        self.sc_start_button = QtWidgets.QPushButton(self.widget_6)
        self.sc_start_button.setStyleSheet(
            "QPushButton{\n"
            "border-radius:15;\n"
            "background-color:rgb(0, 150, 0);\n"
            "color:rgb(255, 255, 255);\n"
            'font: 25pt "Forte";\n'
            "}\n"
            "QPushButton:hover{\n"
            "background-color:rgb(0, 194, 0);\n"
            "}"
        )
        self.sc_start_button.setObjectName("sc_start_button")
        self.horizontalLayout_4.addWidget(self.sc_start_button)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.tabWidget.addTab(self.sc_tab, "")
        self.m_tab = QtWidgets.QWidget()
        self.m_tab.setStyleSheet("background-color: rgb(239, 239, 239);\n" "")
        self.m_tab.setObjectName("m_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.m_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.m_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.m_EEG_pLot_widget = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(
            self.m_EEG_pLot_widget.sizePolicy().hasHeightForWidth()
        )
        self.m_EEG_pLot_widget.setSizePolicy(sizePolicy)
        self.m_EEG_pLot_widget.setMinimumSize(QtCore.QSize(150, 111))
        self.m_EEG_pLot_widget.setSizeIncrement(QtCore.QSize(1, 1))
        self.m_EEG_pLot_widget.setStyleSheet(
            "background-color:rgb(255, 255, 255);\n" "border-radius:5px;"
        )
        self.m_EEG_pLot_widget.setObjectName("m_EEG_pLot_widget")
        self.horizontalLayout_13.addWidget(self.m_EEG_pLot_widget)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(5, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.m_intention_label = QtWidgets.QLabel(self.widget_4)
        self.m_intention_label.setStyleSheet("font: 700 16pt; ")
        self.m_intention_label.setObjectName("m_intention_label")
        self.verticalLayout_20.addWidget(self.m_intention_label)
        self.m_prediction_label = QtWidgets.QLabel(self.widget_4)
        self.m_prediction_label.setStyleSheet("font: 550 12pt; ")
        self.m_prediction_label.setObjectName("m_prediction_label")
        self.verticalLayout_20.addWidget(self.m_prediction_label)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_20.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.m_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.widget_31 = QtWidgets.QWidget(self.widget_2)
        self.widget_31.setObjectName("widget_31")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_31)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_34 = QtWidgets.QWidget(self.widget_31)
        self.widget_34.setStyleSheet(
            "qproperty-alignment: AlignCenter;\n"
            "text-align:center;\n"
            "font: 700 16pt; "
        )
        self.widget_34.setObjectName("widget_34")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_34)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_14.addItem(spacerItem3)
        self.m_fes_label = QtWidgets.QLabel(self.widget_34)
        self.m_fes_label.setStyleSheet("font: 700 16pt; ")
        self.m_fes_label.setObjectName("m_fes_label")
        self.horizontalLayout_14.addWidget(self.m_fes_label)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_14.addItem(spacerItem4)
        self.verticalLayout_21.addWidget(self.widget_34)
        self.widget_33 = QtWidgets.QWidget(self.widget_31)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_33.sizePolicy().hasHeightForWidth())
        self.widget_33.setSizePolicy(sizePolicy)
        self.widget_33.setObjectName("widget_33")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_33)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.widget_37 = QtWidgets.QWidget(self.widget_33)
        self.widget_37.setObjectName("widget_37")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_37)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.m_g_fes_label = QtWidgets.QLabel(self.widget_37)
        self.m_g_fes_label.setStyleSheet("font: 580 12pt; ")
        self.m_g_fes_label.setObjectName("m_g_fes_label")
        self.verticalLayout_23.addWidget(self.m_g_fes_label)
        self.fes_g_progressBar = QtWidgets.QProgressBar(self.widget_37)
        self.fes_g_progressBar.setProperty("value", 24)
        self.fes_g_progressBar.setObjectName("fes_g_progressBar")
        self.verticalLayout_23.addWidget(self.fes_g_progressBar)
        self.horizontalLayout_16.addWidget(self.widget_37)
        self.line_4 = QtWidgets.QFrame(self.widget_33)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_16.addWidget(self.line_4)
        self.widget_38 = QtWidgets.QWidget(self.widget_33)
        self.widget_38.setObjectName("widget_38")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_38)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.m_r_fes_label = QtWidgets.QLabel(self.widget_38)
        self.m_r_fes_label.setStyleSheet("font: 580 12pt; ")
        self.m_r_fes_label.setObjectName("m_r_fes_label")
        self.verticalLayout_24.addWidget(self.m_r_fes_label)
        self.fes_r_progressBar = QtWidgets.QProgressBar(self.widget_38)
        self.fes_r_progressBar.setProperty("value", 24)
        self.fes_r_progressBar.setObjectName("fes_r_progressBar")
        self.verticalLayout_24.addWidget(self.fes_r_progressBar)
        self.horizontalLayout_16.addWidget(self.widget_38)
        self.verticalLayout_21.addWidget(self.widget_33)
        self.horizontalLayout_12.addWidget(self.widget_31)
        self.line_3 = QtWidgets.QFrame(self.widget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_12.addWidget(self.line_3)
        self.widget_32 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_32.sizePolicy().hasHeightForWidth())
        self.widget_32.setSizePolicy(sizePolicy)
        self.widget_32.setObjectName("widget_32")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_32)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.widget_36 = QtWidgets.QWidget(self.widget_32)
        self.widget_36.setObjectName("widget_36")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_36)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem5 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_15.addItem(spacerItem5)
        self.m_glove_label = QtWidgets.QLabel(self.widget_36)
        self.m_glove_label.setStyleSheet("font: 700 16pt; ")
        self.m_glove_label.setObjectName("m_glove_label")
        self.horizontalLayout_15.addWidget(self.m_glove_label)
        spacerItem6 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout_22.addWidget(self.widget_36)
        self.widget_35 = QtWidgets.QWidget(self.widget_32)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_35.sizePolicy().hasHeightForWidth())
        self.widget_35.setSizePolicy(sizePolicy)
        self.widget_35.setObjectName("widget_35")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_35)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_40 = QtWidgets.QWidget(self.widget_35)
        self.widget_40.setObjectName("widget_40")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.widget_40)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.m_g_glove_label = QtWidgets.QLabel(self.widget_40)
        self.m_g_glove_label.setStyleSheet("font: 580 12pt; ")
        self.m_g_glove_label.setObjectName("m_g_glove_label")
        self.verticalLayout_25.addWidget(self.m_g_glove_label)
        self.glove_g_progressBar = QtWidgets.QProgressBar(self.widget_40)
        self.glove_g_progressBar.setProperty("value", 24)
        self.glove_g_progressBar.setObjectName("glove_g_progressBar")
        self.verticalLayout_25.addWidget(self.glove_g_progressBar)
        self.horizontalLayout_17.addWidget(self.widget_40)
        self.line_5 = QtWidgets.QFrame(self.widget_35)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_17.addWidget(self.line_5)
        self.widget_39 = QtWidgets.QWidget(self.widget_35)
        self.widget_39.setObjectName("widget_39")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.widget_39)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.m_r_glove_label = QtWidgets.QLabel(self.widget_39)
        self.m_r_glove_label.setStyleSheet("font: 580 12pt; ")
        self.m_r_glove_label.setObjectName("m_r_glove_label")
        self.verticalLayout_26.addWidget(self.m_r_glove_label)
        self.glove_r_progressBar = QtWidgets.QProgressBar(self.widget_39)
        self.glove_r_progressBar.setProperty("value", 24)
        self.glove_r_progressBar.setObjectName("glove_r_progressBar")
        self.verticalLayout_26.addWidget(self.glove_r_progressBar)
        self.horizontalLayout_17.addWidget(self.widget_39)
        self.verticalLayout_22.addWidget(self.widget_35)
        self.horizontalLayout_12.addWidget(self.widget_32)
        self.verticalLayout.addWidget(self.widget_2)
        self.tabWidget.addTab(self.m_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 727, 38))
        self.menubar.setStyleSheet(
            "QMenuBar {\n"
            "    color:rgb(255, 255, 255);\n"
            "    font: 585 15pt; \n"
            "}\n"
            "QMenuBar::item {\n"
            "    background-color: #444444;\n"
            "    color: white;\n"
            "    padding: 5px 10px;\n"
            "}\n"
            "QMenuBar::item:selected { /* when mouse hover */\n"
            "    background-color: #A9A9A9;\n"
            "}\n"
            ""
        )
        self.menubar.setObjectName("menubar")
        self.menuBack = QtWidgets.QMenu(self.menubar)
        self.menuBack.setObjectName("menuBack")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuBack.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calibration"))
        self.fes_sc_label.setText(_translate("MainWindow", "FES Initial Parameters"))
        self.grasping_fes_sc_label.setText(_translate("MainWindow", "Grasping:"))
        self.g_cv_fes_sc_label.setText(_translate("MainWindow", "Calibrated Value:"))
        self.releasing_fes_sc_label.setText(_translate("MainWindow", "Releasing:"))
        self.r_cv_fes_sc_label.setText(_translate("MainWindow", "Calibrated Value:"))
        self.glove_sc_label.setText(_translate("MainWindow", "Glove State"))
        self.grasping_glove_sc_label.setText(_translate("MainWindow", "Grasping:"))
        self.grasping_glove_sc_value_label.setText(_translate("MainWindow", "Done"))
        self.releasing_glove_sc_label.setText(_translate("MainWindow", "Releasing:"))
        self.releasing_glove_sc_value_label.setText(
            _translate("MainWindow", "In Progress")
        )
        self.instructions_sc_label.setText(_translate("MainWindow", "Instructions"))
        self.sc_start_button.setText(_translate("MainWindow", "     Start     "))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.sc_tab),
            _translate("MainWindow", "System Calibration"),
        )
        self.m_intention_label.setText(_translate("MainWindow", "Patient Intention"))
        self.m_prediction_label.setText(_translate("MainWindow", "Prediction"))
        self.m_fes_label.setText(_translate("MainWindow", "FES"))
        self.m_g_fes_label.setText(_translate("MainWindow", "Grasping"))
        self.m_r_fes_label.setText(_translate("MainWindow", "Releasing"))
        self.m_glove_label.setText(_translate("MainWindow", "Glove"))
        self.m_g_glove_label.setText(_translate("MainWindow", "Grasping"))
        self.m_r_glove_label.setText(_translate("MainWindow", "Releasing"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.m_tab), _translate("MainWindow", "Monitor")
        )
        self.menuBack.setTitle(_translate("MainWindow", "Back"))
    



class MainWindowApp(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        
        self.udp_host = '0.0.0.0'  # Listen on all interfaces
        self.udp_port = 12345  # Port to listen on

        self.esp32_ip = '192.168.137.35'  # IP address of your ESP32
        
        self.fes_grasping_bar_value = 0
        self.fes_releasing_bar_value = 0
        self.glove_grasping_bar_value = 0
        self.glove_releasing_bar_value = 0
        
        self.prediction_list = [0, 1, 0, 0, 1, 1, 0, 0, 0, 1]
        self.current_prediction = 0
        self.counter = 0
        # Serial port configuration
        serial_port = 'COM4'  # Update with your actual COM port
        baud_rate = 115200
        self.ser = serial.Serial(serial_port, baud_rate)
        
        self.received_message = ''
        
        self.glove_state_list = [0, 0]
        
        self.glove_current_state = GLOVE_STATE_RELEASE
        # Connect the button to the slot
        self.sc_start_button.clicked.connect(self.start)
        
    def start(self):
    # Get the values from the input fields
        self.calibrated_grasping_fes_value = self.g_fes_sc_input.value()
        self.calibrated_releasing_fes_value = self.r_fes_sc_input.value()
        self.set_cv_text_fields()

        # # Create a QTimer for monitoring
        # self.monitoring_timer = QTimer(self)
        # # Connect the timeout signal to the update_monitoring function
        # self.monitoring_timer.timeout.connect(self.update_monitoring)
        # # Start the timer with a 1000ms interval (1 second)
        # self.monitoring_timer.start(1000)

        # Create a QTimer for prediction
        self.prediction_timer = QTimer(self)
        # Connect the timeout signal to the update_prediction function
        self.prediction_timer.timeout.connect(self.udp_send)
        # Start the timer with a 2000ms interval (2 seconds)
        self.prediction_timer.start(4000)
        
        # Create a QTimer for receive
        self.receive_timer = QTimer(self)
        # Connect the timeout signal to the update_prediction function
        self.receive_timer.timeout.connect(self.read_from_port)
        # Start the timer with a 2000ms interval (2 seconds)
        self.receive_timer.start(200)
        
    def set_cv_text_fields(self):
        self.r_cv_fes_sc_input.setReadOnly(False)
        self.g_cv_fes_sc_input.setReadOnly(False)
        self.g_cv_fes_sc_input.setText(str(self.calibrated_grasping_fes_value))
        self.r_cv_fes_sc_input.setText(str(self.calibrated_releasing_fes_value))
        self.g_cv_fes_sc_input.setReadOnly(True)
        self.r_cv_fes_sc_input.setReadOnly(True)
        
    def get_fes_progress(self):
        self.fes_grasping_bar_value = (self.rmsg_values[FES_ROM_RELEASE]/80)*100
        self.fes_releasing_bar_value = (self.rmsg_values[FES_ROM_GRASP]/80)*100
        self.update_fes_progress_bar()
        
    def update_fes_progress_bar(self):
        self.fes_g_progressBar.setProperty("value", self.fes_grasping_bar_value)
        self.fes_r_progressBar.setProperty("value", self.fes_releasing_bar_value)
        
    def get_glove_progress(self):
        self.glove_grasping_bar_value = (sum(self.rmsg_values))/int(len(self.rmsg_values))
        self.glove_releasing_bar_value = (sum(self.rmsg_values))/int(len(self.rmsg_values))
        self.update_glove_progress_bar()
        
    def update_glove_progress_bar(self):
        self.glove_g_progressBar.setProperty("value", self.glove_grasping_bar_value)
        self.glove_r_progressBar.setProperty("value", self.glove_releasing_bar_value)
        
    def update_monitoring(self):
        if self.rmsg_header == FES_HEADER:
            if self.rmsg_sub_header == FES_PARAM_SUBHEADER:
                self.get_fes_progress()
        elif self.rmsg_header == GLOVE_HEADER:
            if self.rmsg_sub_header == GLOVE_STATE_SUBHEADER:
                self.glove_current_state = self.rmsg_values[0] 
            elif self.rmsg_sub_header == GLOVE_ANGLES_SUBHEADER:
                self.get_glove_progress()
        
    def get_predicrion(self):
        # if self.prediction_list[self.counter] == 0:
            self.m_prediction_label.setText(self.received_message)
            self.current_prediction = self.prediction_list[self.counter]
        # if self.prediction_list[self.counter] == 1:
            # self.m_prediction_label.setText("Releasing")
            
    def update_prediction(self):
        self.get_predicrion()
        self.counter += 1
        if self.counter == 10:
            self.counter = 0
            
    def read_from_port(self):
        if self.ser.in_waiting > 0:
            message = self.ser.readline().decode('utf-8').strip()
            self.received_message = message
            self.rmsg_header, self.rmsg_sub_header, self.rmsg_values = MessageDecoding(self.received_message)
            if self.rmsg_header is None:
                return
            self.update_monitoring()
            
    def udp_send(self):
        addr = (self.esp32_ip, self.udp_port)
        client_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        prediction = MessageEncoding(MASTER_HEADER, MASTER_DECISION_SUBHEADER, self.current_prediction)
        client_socket.sendto(prediction.encode(), addr)
        print(f'Sent: {prediction}')
        self.update_prediction()
            
    
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = MainWindowApp()
    main_window.show()
    sys.exit(app.exec_())