# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from datetime import date
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 663)
        MainWindow.setStyleSheet("background-color:#265073;\n" "\n" "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setStyleSheet(
            "QPushButton{\n"
            "background-color:#2D9596;\n"
            "border-radius:5%;\n"
            "color:rgb(255, 255, 255);\n"
            'font: 20pt "Forte";\n'
            "}\n"
            "QPushButton:hover{\n"
            "background-color:rgb(67, 183, 255);\n"
            "}"
        )
        self.back_button.setObjectName("back_button")
        self.gridLayout_10.addWidget(self.back_button, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            600, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_10.addItem(spacerItem, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.paramters_tab = QtWidgets.QWidget()
        self.paramters_tab.setStyleSheet("background-color: rgb(239, 239, 239);\n" "")
        self.paramters_tab.setObjectName("paramters_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.paramters_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget = QtWidgets.QWidget(self.paramters_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stimulation_settings_label = QtWidgets.QLabel(self.widget_3)
        self.stimulation_settings_label.setStyleSheet("font: 700 20pt; ")
        self.stimulation_settings_label.setObjectName("stimulation_settings_label")
        self.verticalLayout_2.addWidget(self.stimulation_settings_label)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setObjectName("gridLayout")
        self.pulse_w_label = QtWidgets.QLabel(self.widget_4)
        self.pulse_w_label.setStyleSheet("font: 600 12pt; ")
        self.pulse_w_label.setObjectName("pulse_w_label")
        self.gridLayout.addWidget(self.pulse_w_label, 3, 0, 1, 1)
        self.pulse_intensity_label = QtWidgets.QLabel(self.widget_4)
        self.pulse_intensity_label.setStyleSheet("font: 600 12pt; ")
        self.pulse_intensity_label.setObjectName("pulse_intensity_label")
        self.gridLayout.addWidget(self.pulse_intensity_label, 2, 0, 1, 1)
        self.pulse_freq_label = QtWidgets.QLabel(self.widget_4)
        self.pulse_freq_label.setStyleSheet("font: 600 12pt; ")
        self.pulse_freq_label.setObjectName("pulse_freq_label")
        self.gridLayout.addWidget(self.pulse_freq_label, 1, 0, 1, 1)
        self.pulse_freq_value_label = QtWidgets.QLabel(self.widget_4)
        self.pulse_freq_value_label.setStyleSheet("font: 500 12pt; ")
        self.pulse_freq_value_label.setObjectName("pulse_freq_value_label")
        self.gridLayout.addWidget(self.pulse_freq_value_label, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setStyleSheet("font: 500 12pt; ")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 1, 1, 1)
        self.waveform_value_label = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.waveform_value_label.sizePolicy().hasHeightForWidth()
        )
        self.waveform_value_label.setSizePolicy(sizePolicy)
        self.waveform_value_label.setStyleSheet("font: 500 12pt; ")
        self.waveform_value_label.setObjectName("waveform_value_label")
        self.gridLayout.addWidget(self.waveform_value_label, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.pulse_intensity_value_label = QtWidgets.QLabel(self.widget_4)
        self.pulse_intensity_value_label.setStyleSheet("font: 500 12pt; ")
        self.pulse_intensity_value_label.setObjectName("pulse_intensity_value_label")
        self.gridLayout.addWidget(self.pulse_intensity_value_label, 2, 1, 1, 1)
        self.waveform_label = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.waveform_label.sizePolicy().hasHeightForWidth()
        )
        self.waveform_label.setSizePolicy(sizePolicy)
        self.waveform_label.setStyleSheet("font: 600 12pt; ")
        self.waveform_label.setObjectName("waveform_label")
        self.gridLayout.addWidget(self.waveform_label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_4)
        self.gridLayout_9.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.paramters_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_label = QtWidgets.QLabel(self.widget_2)
        self.add_label.setStyleSheet("font: 600 12pt; ")
        self.add_label.setObjectName("add_label")
        self.gridLayout_2.addWidget(self.add_label, 9, 0, 1, 1)
        self.add_textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.add_textEdit.setStyleSheet("font: 500 12pt; ")
        self.add_textEdit.setObjectName("add_textEdit")
        self.gridLayout_2.addWidget(self.add_textEdit, 10, 0, 1, 3)
        self.grasping_type_comboBox = QtWidgets.QComboBox(self.widget_2)
        self.grasping_type_comboBox.setMinimumSize(QtCore.QSize(0, 28))
        self.grasping_type_comboBox.setStyleSheet("font: 500 12pt; ")
        self.grasping_type_comboBox.setObjectName("grasping_type_comboBox")
        self.grasping_type_comboBox.addItem("")
        self.grasping_type_comboBox.addItem("")
        self.grasping_type_comboBox.addItem("")
        self.grasping_type_comboBox.addItem("")
        self.grasping_type_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.grasping_type_comboBox, 2, 0, 1, 3)
        self.move_angle_label = QtWidgets.QLabel(self.widget_2)
        self.move_angle_label.setStyleSheet("font: 600 12pt; ")
        self.move_angle_label.setObjectName("move_angle_label")
        self.gridLayout_2.addWidget(self.move_angle_label, 3, 0, 1, 1)
        self.correct_radioButton = QtWidgets.QRadioButton(self.widget_2)
        self.correct_radioButton.setStyleSheet("font: 500 12pt; ")
        self.correct_radioButton.setObjectName("correct_radioButton")
        self.gridLayout_2.addWidget(self.correct_radioButton, 6, 0, 1, 1)
        self.yes_radioButton = QtWidgets.QRadioButton(self.widget_2)
        self.yes_radioButton.setStyleSheet("font: 500 12pt; ")
        self.yes_radioButton.setObjectName("yes_radioButton")
        self.gridLayout_2.addWidget(self.yes_radioButton, 8, 0, 1, 1)
        self.no_radioButton = QtWidgets.QRadioButton(self.widget_2)
        self.no_radioButton.setStyleSheet("font: 500 12pt; ")
        self.no_radioButton.setObjectName("no_radioButton")
        self.gridLayout_2.addWidget(self.no_radioButton, 8, 1, 1, 1)
        self.feedback_label = QtWidgets.QLabel(self.widget_2)
        self.feedback_label.setStyleSheet("font: 600 12pt; ")
        self.feedback_label.setObjectName("feedback_label")
        self.gridLayout_2.addWidget(self.feedback_label, 5, 0, 1, 1)
        self.incorrect_radioButton = QtWidgets.QRadioButton(self.widget_2)
        self.incorrect_radioButton.setStyleSheet("font: 500 12pt; ")
        self.incorrect_radioButton.setObjectName("incorrect_radioButton")
        self.gridLayout_2.addWidget(self.incorrect_radioButton, 6, 1, 1, 1)
        self.par_label = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.par_label.sizePolicy().hasHeightForWidth())
        self.par_label.setSizePolicy(sizePolicy)
        self.par_label.setStyleSheet("font: 600 12pt; ")
        self.par_label.setObjectName("par_label")
        self.gridLayout_2.addWidget(self.par_label, 7, 0, 1, 2)
        self.acc_label = QtWidgets.QLabel(self.widget_2)
        self.acc_label.setStyleSheet("font: 600 12pt; ")
        self.acc_label.setObjectName("acc_label")
        self.gridLayout_2.addWidget(self.acc_label, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_2.addItem(spacerItem2, 11, 1, 1, 1)
        self.acc_value_label = QtWidgets.QLabel(self.widget_2)
        self.acc_value_label.setStyleSheet("font: 500 12pt; ")
        self.acc_value_label.setObjectName("acc_value_label")
        self.gridLayout_2.addWidget(self.acc_value_label, 4, 1, 1, 1)
        self.move_angle_value_label = QtWidgets.QLabel(self.widget_2)
        self.move_angle_value_label.setStyleSheet("font: 500 12pt; ")
        self.move_angle_value_label.setObjectName("move_angle_value_label")
        self.gridLayout_2.addWidget(self.move_angle_value_label, 3, 1, 1, 1)
        self.grasping_type_label = QtWidgets.QLabel(self.widget_2)
        self.grasping_type_label.setStyleSheet("font: 600 12pt; ")
        self.grasping_type_label.setObjectName("grasping_type_label")
        self.gridLayout_2.addWidget(self.grasping_type_label, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum
        )
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.widget_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.paramters_tab, "")
        self.overveiw_tab = QtWidgets.QWidget()
        self.overveiw_tab.setStyleSheet("background-color: rgb(239, 239, 239);\n" "")
        self.overveiw_tab.setObjectName("overveiw_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.overveiw_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_24 = QtWidgets.QLabel(self.overveiw_tab)
        self.label_24.setStyleSheet("font: 600 12pt; ")
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 9, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.overveiw_tab)
        self.label_21.setStyleSheet("font: 600 12pt; ")
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 3, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.overveiw_tab)
        self.label_22.setStyleSheet("font: 600 12pt; ")
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 4, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.overveiw_tab)
        self.dateEdit_2.setStyleSheet("font: 500 12pt; ")
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_3.addWidget(self.dateEdit_2, 9, 1, 1, 1)
        self.session_date_dateEdit = QtWidgets.QDateEdit(self.overveiw_tab)
        self.session_date_dateEdit.setStyleSheet("font: 500 12pt; ")
        self.session_date_dateEdit.setObjectName("session_date_dateEdit")
        self.gridLayout_3.addWidget(self.session_date_dateEdit, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum
        )
        self.gridLayout_3.addItem(spacerItem4, 8, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.overveiw_tab)
        self.label_19.setStyleSheet("font: 600 12pt; ")
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.overveiw_tab)
        self.label_20.setStyleSheet("font: 600 12pt; ")
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(
            200, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_3.addItem(spacerItem5, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(
            20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_3.addItem(spacerItem6, 10, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.overveiw_tab)
        self.label_27.setStyleSheet("font: 500 12pt; ")
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 1, 1, 1)
        self.session_date_label = QtWidgets.QLabel(self.overveiw_tab)
        self.session_date_label.setStyleSheet("font: 600 12pt; ")
        self.session_date_label.setObjectName("session_date_label")
        self.gridLayout_3.addWidget(self.session_date_label, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.overveiw_tab)
        self.label_23.setAutoFillBackground(False)
        self.label_23.setStyleSheet("font: 600 12pt; ")
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 6, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.overveiw_tab)
        self.label_26.setStyleSheet("font: 500 12pt; ")
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 2, 1, 1, 1)
        self.textEdit_6 = QtWidgets.QTextEdit(self.overveiw_tab)
        self.textEdit_6.setStyleSheet("font: 500 12pt; ")
        self.textEdit_6.setObjectName("textEdit_6")
        self.gridLayout_3.addWidget(self.textEdit_6, 5, 0, 1, 2)
        self.textEdit_5 = QtWidgets.QTextEdit(self.overveiw_tab)
        self.textEdit_5.setStyleSheet("font: 500 12pt; ")
        self.textEdit_5.setObjectName("textEdit_5")
        self.gridLayout_3.addWidget(self.textEdit_5, 7, 0, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.overveiw_tab)
        self.label_25.setStyleSheet("font: 500 12pt; ")
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 1, 1, 1, 1)
        self.tabWidget.addTab(self.overveiw_tab, "")
        self.assesment_tab = QtWidgets.QWidget()
        self.assesment_tab.setStyleSheet("background-color: rgb(239, 239, 239);\n" "")
        self.assesment_tab.setObjectName("assesment_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.assesment_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.assesment_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_30 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setStyleSheet("font: 700 20pt; ")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_4.addWidget(self.label_30)
        self.verticalLayout_4.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_32 = QtWidgets.QLabel(self.widget_8)
        self.label_32.setStyleSheet("font: 600 12pt; ")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.textEdit_8 = QtWidgets.QTextEdit(self.widget_8)
        self.textEdit_8.setStyleSheet("font: 500 12pt; ")
        self.textEdit_8.setObjectName("textEdit_8")
        self.verticalLayout_6.addWidget(self.textEdit_8)
        self.label_34 = QtWidgets.QLabel(self.widget_8)
        self.label_34.setStyleSheet("font: 600 12pt; ")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_6.addWidget(self.label_34)
        self.textEdit_7 = QtWidgets.QTextEdit(self.widget_8)
        self.textEdit_7.setStyleSheet("font: 500 12pt; ")
        self.textEdit_7.setObjectName("textEdit_7")
        self.verticalLayout_6.addWidget(self.textEdit_7)
        self.label_36 = QtWidgets.QLabel(self.widget_8)
        self.label_36.setStyleSheet("font: 600 12pt; ")
        self.label_36.setObjectName("label_36")
        self.verticalLayout_6.addWidget(self.label_36)
        self.checkBox = QtWidgets.QCheckBox(self.widget_8)
        self.checkBox.setStyleSheet("font: 500 12pt; ")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_8)
        self.checkBox_2.setStyleSheet("font: 500 12pt; ")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_6.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_8)
        self.checkBox_3.setStyleSheet("font: 500 12pt; ")
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_6.addWidget(self.checkBox_3)
        self.label_41 = QtWidgets.QLabel(self.widget_8)
        self.label_41.setStyleSheet("font: 600 12pt; ")
        self.label_41.setObjectName("label_41")
        self.verticalLayout_6.addWidget(self.label_41)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_8)
        self.textEdit_2.setStyleSheet("font: 500 12pt; ")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_6.addWidget(self.textEdit_2)
        self.verticalLayout_4.addWidget(self.widget_8)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.assesment_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_9 = QtWidgets.QWidget(self.widget_6)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_31 = QtWidgets.QLabel(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setStyleSheet("font: 700 20pt; ")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_5.addWidget(self.label_31)
        self.verticalLayout_3.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setStyleSheet("")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_47 = QtWidgets.QLabel(self.widget_10)
        self.label_47.setStyleSheet("font: 600 12pt; ")
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 8, 0, 1, 3)
        self.label_48 = QtWidgets.QLabel(self.widget_10)
        self.label_48.setStyleSheet("font: 600 12pt; ")
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 10, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.widget_10)
        self.textEdit.setStyleSheet("font: 500 12pt; ")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 11, 0, 1, 4)
        self.label_46 = QtWidgets.QLabel(self.widget_10)
        self.label_46.setStyleSheet("font: 600 12pt; ")
        self.label_46.setObjectName("label_46")
        self.gridLayout_4.addWidget(self.label_46, 6, 0, 1, 3)
        self.label_45 = QtWidgets.QLabel(self.widget_10)
        self.label_45.setStyleSheet("font: 600 12pt; ")
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 4, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.widget_10)
        self.label_44.setStyleSheet("font: 600 12pt; ")
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 2, 0, 1, 3)
        self.label_43 = QtWidgets.QLabel(self.widget_10)
        self.label_43.setStyleSheet("font: 600 12pt; ")
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 0, 1, 3)
        self.textEdit_9 = QtWidgets.QTextEdit(self.widget_10)
        self.textEdit_9.setStyleSheet("font: 500 12pt; ")
        self.textEdit_9.setObjectName("textEdit_9")
        self.gridLayout_4.addWidget(self.textEdit_9, 5, 0, 1, 4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_5.setStyleSheet("font: 500 12pt; ")
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_4.addWidget(self.radioButton_5, 1, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_6.setStyleSheet("font: 500 12pt; ")
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_4.addWidget(self.radioButton_6, 1, 1, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_7.setStyleSheet("font: 500 12pt; ")
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_4.addWidget(self.radioButton_7, 3, 0, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_8.setStyleSheet("font: 500 12pt; ")
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_4.addWidget(self.radioButton_8, 3, 1, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_9.setStyleSheet("font: 500 12pt; ")
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_4.addWidget(self.radioButton_9, 7, 0, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_10.setStyleSheet("font: 500 12pt; ")
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_4.addWidget(self.radioButton_10, 7, 1, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_11.setStyleSheet("font: 500 12pt; ")
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout_4.addWidget(self.radioButton_11, 9, 0, 1, 1)
        self.radioButton_12 = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_12.setStyleSheet("font: 500 12pt; ")
        self.radioButton_12.setObjectName("radioButton_12")
        self.gridLayout_4.addWidget(self.radioButton_12, 9, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_10)
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.tabWidget.addTab(self.assesment_tab, "")
        self.feedback_tab = QtWidgets.QWidget()
        self.feedback_tab.setStyleSheet("background-color: rgb(239, 239, 239);\n" "")
        self.feedback_tab.setObjectName("feedback_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.feedback_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_24 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_24.setStyleSheet("font: 500 12pt; ")
        self.radioButton_24.setObjectName("radioButton_24")
        self.gridLayout_5.addWidget(self.radioButton_24, 2, 3, 1, 1)
        self.radioButton_27 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_27.setStyleSheet("font: 500 12pt; ")
        self.radioButton_27.setObjectName("radioButton_27")
        self.gridLayout_5.addWidget(self.radioButton_27, 4, 1, 1, 1)
        self.radioButton_33 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_33.setStyleSheet("font: 500 12pt; ")
        self.radioButton_33.setObjectName("radioButton_33")
        self.gridLayout_5.addWidget(self.radioButton_33, 6, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.feedback_tab)
        self.label_28.setStyleSheet("font: 600 12pt; ")
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 3, 0, 1, 2)
        self.textEdit_3 = QtWidgets.QTextEdit(self.feedback_tab)
        self.textEdit_3.setStyleSheet("font: 500 12pt; ")
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_5.addWidget(self.textEdit_3, 10, 0, 1, 5)
        self.label_29 = QtWidgets.QLabel(self.feedback_tab)
        self.label_29.setStyleSheet("font: 600 12pt; ")
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 5, 0, 1, 3)
        self.radioButton_38 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_38.setStyleSheet("font: 500 12pt; ")
        self.radioButton_38.setObjectName("radioButton_38")
        self.gridLayout_5.addWidget(self.radioButton_38, 8, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum
        )
        self.gridLayout_5.addItem(spacerItem7, 0, 2, 1, 1)
        self.radioButton_29 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_29.setStyleSheet("font: 500 12pt; ")
        self.radioButton_29.setObjectName("radioButton_29")
        self.gridLayout_5.addWidget(self.radioButton_29, 4, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.feedback_tab)
        self.label_17.setStyleSheet("font: 600 12pt; ")
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 3)
        self.label_42 = QtWidgets.QLabel(self.feedback_tab)
        self.label_42.setStyleSheet("font: 600 12pt; ")
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 9, 0, 1, 2)
        self.radioButton_36 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_36.setStyleSheet("font: 500 12pt; ")
        self.radioButton_36.setObjectName("radioButton_36")
        self.gridLayout_5.addWidget(self.radioButton_36, 8, 0, 1, 1)
        self.radioButton_39 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_39.setStyleSheet("font: 500 12pt; ")
        self.radioButton_39.setObjectName("radioButton_39")
        self.gridLayout_5.addWidget(self.radioButton_39, 8, 3, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_19.setStyleSheet("font: 500 12pt; ")
        self.radioButton_19.setObjectName("radioButton_19")
        self.gridLayout_5.addWidget(self.radioButton_19, 2, 2, 1, 1)
        self.radioButton_25 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_25.setStyleSheet("font: 500 12pt; ")
        self.radioButton_25.setObjectName("radioButton_25")
        self.gridLayout_5.addWidget(self.radioButton_25, 2, 4, 1, 1)
        self.radioButton_35 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_35.setStyleSheet("font: 500 12pt; ")
        self.radioButton_35.setObjectName("radioButton_35")
        self.gridLayout_5.addWidget(self.radioButton_35, 6, 4, 1, 1)
        self.radioButton_26 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_26.setStyleSheet("font: 500 12pt; ")
        self.radioButton_26.setObjectName("radioButton_26")
        self.gridLayout_5.addWidget(self.radioButton_26, 4, 0, 1, 1)
        self.radioButton_18 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_18.setStyleSheet("font: 500 12pt; ")
        self.radioButton_18.setObjectName("radioButton_18")
        self.gridLayout_5.addWidget(self.radioButton_18, 2, 1, 1, 1)
        self.radioButton_31 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_31.setStyleSheet("font: 500 12pt; ")
        self.radioButton_31.setObjectName("radioButton_31")
        self.gridLayout_5.addWidget(self.radioButton_31, 6, 0, 1, 1)
        self.radioButton_40 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_40.setStyleSheet("font: 500 12pt; ")
        self.radioButton_40.setObjectName("radioButton_40")
        self.gridLayout_5.addWidget(self.radioButton_40, 8, 4, 1, 1)
        self.radioButton_34 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_34.setStyleSheet("font: 500 12pt; ")
        self.radioButton_34.setObjectName("radioButton_34")
        self.gridLayout_5.addWidget(self.radioButton_34, 6, 3, 1, 1)
        self.radioButton_32 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_32.setStyleSheet("font: 500 12pt; ")
        self.radioButton_32.setObjectName("radioButton_32")
        self.gridLayout_5.addWidget(self.radioButton_32, 6, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.feedback_tab)
        self.label_33.setStyleSheet("font: 600 12pt; ")
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 7, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(
            20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_5.addItem(spacerItem8, 11, 3, 1, 1)
        self.radioButton_28 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_28.setStyleSheet("font: 500 12pt; ")
        self.radioButton_28.setObjectName("radioButton_28")
        self.gridLayout_5.addWidget(self.radioButton_28, 4, 2, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_17.setStyleSheet("font: 500 12pt; ")
        self.radioButton_17.setObjectName("radioButton_17")
        self.gridLayout_5.addWidget(self.radioButton_17, 2, 0, 1, 1)
        self.radioButton_30 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_30.setStyleSheet("font: 500 12pt; ")
        self.radioButton_30.setObjectName("radioButton_30")
        self.gridLayout_5.addWidget(self.radioButton_30, 4, 4, 1, 1)
        self.radioButton_37 = QtWidgets.QRadioButton(self.feedback_tab)
        self.radioButton_37.setStyleSheet("font: 500 12pt; ")
        self.radioButton_37.setObjectName("radioButton_37")
        self.gridLayout_5.addWidget(self.radioButton_37, 8, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.feedback_tab)
        self.pushButton_2.setStyleSheet(
            "QPushButton{\n"
            "background-color:#2D9596;\n"
            "border-radius:5%;\n"
            "color:rgb(255, 255, 255);\n"
            'font: 20pt "Forte";\n'
            "}\n"
            "QPushButton:hover{\n"
            "background-color:rgb(67, 183, 255);\n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 11, 2, 1, 1)
        self.tabWidget.addTab(self.feedback_tab, "")
        self.eval_tab = QtWidgets.QWidget()
        self.eval_tab.setStyleSheet("background-color: rgb(239, 239, 239);\n" "")
        self.eval_tab.setObjectName("eval_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.eval_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_13 = QtWidgets.QWidget(self.eval_tab)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_22 = QtWidgets.QRadioButton(self.widget_13)
        self.radioButton_22.setStyleSheet("font: 500 12pt; ")
        self.radioButton_22.setObjectName("radioButton_22")
        self.gridLayout_8.addWidget(self.radioButton_22, 1, 3, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.widget_13)
        self.label_62.setStyleSheet("font: 600 12pt; ")
        self.label_62.setObjectName("label_62")
        self.gridLayout_8.addWidget(self.label_62, 2, 0, 1, 1)
        self.radioButton_21 = QtWidgets.QRadioButton(self.widget_13)
        self.radioButton_21.setStyleSheet("font: 500 12pt; ")
        self.radioButton_21.setObjectName("radioButton_21")
        self.gridLayout_8.addWidget(self.radioButton_21, 0, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_8.addItem(spacerItem9, 4, 1, 1, 1)
        self.textEdit_11 = QtWidgets.QTextEdit(self.widget_13)
        self.textEdit_11.setStyleSheet("font: 500 12pt; ")
        self.textEdit_11.setObjectName("textEdit_11")
        self.gridLayout_8.addWidget(self.textEdit_11, 3, 0, 1, 5)
        self.radioButton_23 = QtWidgets.QRadioButton(self.widget_13)
        self.radioButton_23.setStyleSheet("font: 500 12pt; ")
        self.radioButton_23.setObjectName("radioButton_23")
        self.gridLayout_8.addWidget(self.radioButton_23, 1, 4, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.widget_13)
        self.label_60.setStyleSheet("font: 600 12pt; ")
        self.label_60.setObjectName("label_60")
        self.gridLayout_8.addWidget(self.label_60, 0, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.widget_13)
        self.label_61.setStyleSheet("font: 600 12pt; ")
        self.label_61.setObjectName("label_61")
        self.gridLayout_8.addWidget(self.label_61, 1, 0, 1, 3)
        self.radioButton_20 = QtWidgets.QRadioButton(self.widget_13)
        self.radioButton_20.setStyleSheet("font: 500 12pt; ")
        self.radioButton_20.setObjectName("radioButton_20")
        self.gridLayout_8.addWidget(self.radioButton_20, 0, 3, 1, 1)
        self.gridLayout_7.addWidget(self.widget_13, 4, 0, 1, 3)
        spacerItem10 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_7.addItem(spacerItem10, 5, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.eval_tab)
        self.label_51.setStyleSheet("font: 700 20pt; ")
        self.label_51.setObjectName("label_51")
        self.gridLayout_7.addWidget(self.label_51, 3, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.eval_tab)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "background-color:#2D9596;\n"
            "border-radius:5%;\n"
            "color:rgb(255, 255, 255);\n"
            'font: 20pt "Forte";\n'
            "}\n"
            "QPushButton:hover{\n"
            "background-color:rgb(67, 183, 255);\n"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 5, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_7.addItem(spacerItem11, 5, 2, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.eval_tab)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_54 = QtWidgets.QLabel(self.widget_11)
        self.label_54.setStyleSheet("font: 600 12pt; ")
        self.label_54.setObjectName("label_54")
        self.gridLayout_6.addWidget(self.label_54, 2, 0, 1, 1)
        self.textEdit_10 = QtWidgets.QTextEdit(self.widget_11)
        self.textEdit_10.setStyleSheet("font: 500 12pt; ")
        self.textEdit_10.setObjectName("textEdit_10")
        self.gridLayout_6.addWidget(self.textEdit_10, 3, 0, 1, 4)
        self.radioButton_13 = QtWidgets.QRadioButton(self.widget_11)
        self.radioButton_13.setStyleSheet("font: 500 12pt; ")
        self.radioButton_13.setObjectName("radioButton_13")
        self.gridLayout_6.addWidget(self.radioButton_13, 0, 2, 1, 1)
        self.radioButton_14 = QtWidgets.QRadioButton(self.widget_11)
        self.radioButton_14.setStyleSheet("font: 500 12pt; ")
        self.radioButton_14.setObjectName("radioButton_14")
        self.gridLayout_6.addWidget(self.radioButton_14, 0, 3, 1, 1)
        self.radioButton_15 = QtWidgets.QRadioButton(self.widget_11)
        self.radioButton_15.setStyleSheet("font: 500 12pt; ")
        self.radioButton_15.setObjectName("radioButton_15")
        self.gridLayout_6.addWidget(self.radioButton_15, 1, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.widget_11)
        self.label_53.setStyleSheet("font: 600 12pt; ")
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 1, 0, 1, 2)
        self.label_52 = QtWidgets.QLabel(self.widget_11)
        self.label_52.setStyleSheet("font: 600 12pt; ")
        self.label_52.setObjectName("label_52")
        self.gridLayout_6.addWidget(self.label_52, 0, 0, 1, 1)
        self.radioButton_16 = QtWidgets.QRadioButton(self.widget_11)
        self.radioButton_16.setStyleSheet("font: 500 12pt; ")
        self.radioButton_16.setObjectName("radioButton_16")
        self.gridLayout_6.addWidget(self.radioButton_16, 1, 3, 1, 1)
        self.gridLayout_7.addWidget(self.widget_11, 2, 0, 1, 3)
        spacerItem12 = QtWidgets.QSpacerItem(
            20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum
        )
        self.gridLayout_7.addItem(spacerItem12, 0, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.eval_tab)
        self.label_50.setStyleSheet("font: 700 20pt; ")
        self.label_50.setObjectName("label_50")
        self.gridLayout_7.addWidget(self.label_50, 1, 0, 1, 3)
        self.tabWidget.addTab(self.eval_tab, "")
        self.gridLayout_10.addWidget(self.tabWidget, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_button.setText(_translate("MainWindow", "Back"))
        self.stimulation_settings_label.setText(
            _translate("MainWindow", "Stimulation Settings:")
        )
        self.pulse_w_label.setText(_translate("MainWindow", "● Pulse Width:"))
        self.pulse_intensity_label.setText(
            _translate("MainWindow", "● Pulse Intensity:")
        )
        self.pulse_freq_label.setText(_translate("MainWindow", "● Pulse Frequency:"))
        self.pulse_freq_value_label.setText(_translate("MainWindow", "40 Hz"))
        self.label_9.setText(_translate("MainWindow", "250 ╬╝s"))
        self.waveform_value_label.setText(_translate("MainWindow", "TENS"))
        self.pulse_intensity_value_label.setText(
            _translate("MainWindow", "G 50 , R 40")
        )
        self.waveform_label.setText(_translate("MainWindow", "● Waveform:"))
        self.add_label.setText(_translate("MainWindow", "Additional:"))
        self.grasping_type_comboBox.setItemText(
            0, _translate("MainWindow", "Cup Holding")
        )
        self.grasping_type_comboBox.setItemText(
            1, _translate("MainWindow", "Pen Holding")
        )
        self.grasping_type_comboBox.setItemText(
            2, _translate("MainWindow", "Key Holding")
        )
        self.grasping_type_comboBox.setItemText(
            3, _translate("MainWindow", "Ball Holding")
        )
        self.grasping_type_comboBox.setItemText(
            4, _translate("MainWindow", "Bottle Holding")
        )
        self.move_angle_label.setText(_translate("MainWindow", "Movement Angle:"))
        self.correct_radioButton.setText(_translate("MainWindow", "Correct"))
        self.yes_radioButton.setText(_translate("MainWindow", "Yes"))
        self.no_radioButton.setText(_translate("MainWindow", "No"))
        self.feedback_label.setText(_translate("MainWindow", "Feedback:"))
        self.incorrect_radioButton.setText(_translate("MainWindow", "Incorrect"))
        self.par_label.setText(
            _translate("MainWindow", "Parameters Adjustment Required:")
        )
        self.acc_label.setText(_translate("MainWindow", "Accuracy:"))
        self.acc_value_label.setText(
            _translate("MainWindow", "-----------------------")
        )
        self.move_angle_value_label.setText(
            _translate("MainWindow", "-----------------------")
        )
        self.grasping_type_label.setText(_translate("MainWindow", "Grasping Type:"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.paramters_tab),
            _translate("MainWindow", "FES Parameters And Feedback Glove"),
        )
        self.label_24.setText(_translate("MainWindow", "Next Session Date:"))
        self.label_21.setText(_translate("MainWindow", "Session Duration:"))
        self.label_22.setText(_translate("MainWindow", "Performance Feedback:"))
        self.label_19.setText(_translate("MainWindow", "Stimulation Protocol:"))
        self.label_20.setText(_translate("MainWindow", "Target Movements:"))
        self.label_27.setText(
            _translate("MainWindow", "--------------------------------- Min")
        )
        self.session_date_label.setText(_translate("MainWindow", "Session Date:"))
        self.label_23.setText(_translate("MainWindow", "Clinician Notes:"))
        self.label_26.setText(
            _translate("MainWindow", "--------------------------------------")
        )
        self.label_25.setText(
            _translate("MainWindow", "--------------------------------------")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.overveiw_tab),
            _translate("MainWindow", "Session Overveiw"),
        )
        self.label_30.setText(_translate("MainWindow", "Overall Progress:"))
        self.label_32.setText(_translate("MainWindow", "● Improvements Observed:"))
        self.label_34.setText(_translate("MainWindow", "● Challenges Noted:"))
        self.label_36.setText(_translate("MainWindow", "● Side effects"))
        self.checkBox.setText(_translate("MainWindow", "Itching"))
        self.checkBox_2.setText(_translate("MainWindow", "Burning"))
        self.checkBox_3.setText(_translate("MainWindow", "Fatigue"))
        self.label_41.setText(_translate("MainWindow", "● Next Steps In Therapy:"))
        self.label_31.setText(_translate("MainWindow", "Recommendations:"))
        self.label_47.setText(_translate("MainWindow", "● Introduce New Exercises:"))
        self.label_48.setText(_translate("MainWindow", "Details:"))
        self.label_46.setText(
            _translate("MainWindow", "● Increase Session Frequency:")
        )
        self.label_45.setText(_translate("MainWindow", "New Settings:"))
        self.label_44.setText(
            _translate("MainWindow", "● Adjust Stimulation Settings:")
        )
        self.label_43.setText(
            _translate("MainWindow", "● Continue Current Protocol:")
        )
        self.radioButton_5.setText(_translate("MainWindow", "Yes"))
        self.radioButton_6.setText(_translate("MainWindow", "No"))
        self.radioButton_7.setText(_translate("MainWindow", "Yes"))
        self.radioButton_8.setText(_translate("MainWindow", "No"))
        self.radioButton_9.setText(_translate("MainWindow", "Yes"))
        self.radioButton_10.setText(_translate("MainWindow", "No"))
        self.radioButton_11.setText(_translate("MainWindow", "Yes"))
        self.radioButton_12.setText(_translate("MainWindow", "No"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.assesment_tab),
            _translate("MainWindow", "Clinical Assesment"),
        )
        self.radioButton_24.setText(_translate("MainWindow", "Agree"))
        self.radioButton_27.setText(_translate("MainWindow", "Disagree"))
        self.radioButton_33.setText(_translate("MainWindow", "Neutral"))
        self.label_28.setText(
            _translate("MainWindow", "● The therapy was comforable")
        )
        self.label_29.setText(
            _translate(
                "MainWindow", "● The experience during the session was painful"
            )
        )
        self.radioButton_38.setText(_translate("MainWindow", "Neutral"))
        self.radioButton_29.setText(_translate("MainWindow", "Agree"))
        self.label_17.setText(
            _translate(
                "MainWindow", "● The experience during the session was satisfying"
            )
        )
        self.label_42.setText(_translate("MainWindow", "Additional Comments:"))
        self.radioButton_36.setText(_translate("MainWindow", "Strongly disagree"))
        self.radioButton_39.setText(_translate("MainWindow", "Agree"))
        self.radioButton_19.setText(_translate("MainWindow", "Neutral"))
        self.radioButton_25.setText(_translate("MainWindow", "Strongly agree"))
        self.radioButton_35.setText(_translate("MainWindow", "Strongly agree"))
        self.radioButton_26.setText(_translate("MainWindow", "Strongly disagree"))
        self.radioButton_18.setText(_translate("MainWindow", "Disagree"))
        self.radioButton_31.setText(_translate("MainWindow", "Strongly disagree"))
        self.radioButton_40.setText(_translate("MainWindow", "Strongly agree"))
        self.radioButton_34.setText(_translate("MainWindow", "Agree"))
        self.radioButton_32.setText(_translate("MainWindow", "Disagree"))
        self.label_33.setText(
            _translate("MainWindow", "● The hand function was improved")
        )
        self.radioButton_28.setText(_translate("MainWindow", "Neutral"))
        self.radioButton_17.setText(_translate("MainWindow", "Strongly disagree"))
        self.radioButton_30.setText(_translate("MainWindow", "Strongly agree"))
        self.radioButton_37.setText(_translate("MainWindow", "Disagree"))
        self.pushButton_2.setText(_translate("MainWindow", "Submit"))
        self.pushButton_2.clicked.connect(self.on_submit)
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.feedback_tab),
            _translate("MainWindow", "Patient Feedback"),
        )
        self.radioButton_22.setText(_translate("MainWindow", "Yes"))
        self.label_62.setText(
            _translate("MainWindow", "● Additional Therapies Suggested:")
        )
        self.radioButton_21.setText(_translate("MainWindow", "No"))
        self.radioButton_23.setText(_translate("MainWindow", "No"))
        self.label_60.setText(_translate("MainWindow", "● Continue Home Exercises:"))
        self.label_61.setText(
            _translate("MainWindow", "● Further Clinical Sessions Needed:")
        )
        self.radioButton_20.setText(_translate("MainWindow", "Yes"))
        self.label_51.setText(_translate("MainWindow", "Future Recommendations:"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.label_54.setText(_translate("MainWindow", "● Remaining Challenges:"))
        self.radioButton_13.setText(_translate("MainWindow", "Yes"))
        self.radioButton_14.setText(_translate("MainWindow", "No"))
        self.radioButton_15.setText(_translate("MainWindow", "Yes"))
        self.label_53.setText(_translate("MainWindow", "● Long-Term Goals Achieved:"))
        self.label_52.setText(_translate("MainWindow", "● Quality Of Life Improved:"))
        self.radioButton_16.setText(_translate("MainWindow", "No"))
        self.label_50.setText(_translate("MainWindow", "Final Progress:"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.eval_tab),
            _translate("MainWindow", "Final Evaluation"),
        )

    def on_submit(self):
        newReport = Report(
            Name="Name",
            Patient_ID="ID",
            Date_of_Birth="DOB",
            Gender="Gender",
            Hand_Dominance="",
            Diagnosis="",
            Referring_Clinician="",
            Rehabilitation_Start_Date="1/1/2000",
            Muscle_Weakness="Yes",
            Muscle_Paralysis="Yes",
            Muscle_Spasticity="Yes",
            Loss_of_Coordination="Yes",
            Tremors="Yes",
            Reduced_Range_of_Motion="Yes",
            Sensory_Loss="Yes",
            Pain="Yes",
            Hand_function_impairment="Yes",
            Muscle_Testing_Score="",
            Number_of_Sessions="3",
            Discharge_Date="1/1/2000",
            Medical_History="",
            Waveform="TENS",
            Pulse_Frequency="40 Hz",
            Pulse_Intensity="G50, R40",
            Pulse_Width="250 μs",
            Movement_Angle_cup="",
            Accuracy_cup="",
            Feedback_cup=(
                "Yes"
                if self.correct_radioButton.isChecked()
                else "No" if self.incorrect_radioButton.isChecked() else ""
            ),
            is_adjustment_Required_cup=(
                "Correct"
                if self.yes_radioButton.isChecked()
                else "Incorrect" if self.no_radioButton.isChecked() else ""
            ),
            Additional_Notes_cup="",
            Movement_Angle_pen="",
            Accuracy_pen="",
            Feedback_pen="",
            is_adjustment_Required_pen=(
                "Correct"
                if self.correct_radioButton.isChecked()
                else "Incorrect" if self.incorrect_radioButton.isChecked() else ""
            ),
            Additional_Notes_pen="",
            Movement_Angle_key="",
            Accuracy_key="",
            Feedback_key=(
                "Yes"
                if self.yes_radioButton.isChecked()
                else "No" if self.no_radioButton.isChecked() else ""
            ),
            is_adjustment_Required_key=(
                "Correct"
                if self.correct_radioButton.isChecked()
                else "Incorrect" if self.incorrect_radioButton.isChecked() else ""
            ),
            Additional_Notes_key="",
            Movement_Angle_ball="",
            Accuracy_ball="",
            Feedback_ball=(
                "Yes"
                if self.yes_radioButton.isChecked()
                else "No" if self.no_radioButton.isChecked() else ""
            ),
            is_adjustment_Required_ball=(
                "Correct"
                if self.correct_radioButton.isChecked()
                else "Incorrect" if self.incorrect_radioButton.isChecked() else ""
            ),
            Additional_Notes_ball="",
            Movement_Angle_bottle="",
            Accuracy_bottle="",
            Feedback_bottle=(
                "Yes"
                if self.yes_radioButton.isChecked()
                else "No" if self.no_radioButton.isChecked() else ""
            ),
            is_adjustment_Required_bottle=(
                "Correct"
                if self.correct_radioButton.isChecked()
                else "Incorrect" if self.incorrect_radioButton.isChecked() else ""
            ),
            Additional_Notes_bottle="",
            Session_Date=date.today(),
            Stimulation_Protocol=self.label_25.text(),
            Target_Movements=self.label_26,
            Session_Duration=self.label_27,
            Performance_Feedback="",
            Clinician_Notes="",
            Improvements_Observed="",
            Challenges_Noted="",
            Side_effects=(
                "Itching"
                if self.checkBox.isChecked()
                else (
                    "Burining"
                    if self.checkBox_2.isChecked()
                    else "Fatigue" if self.checkBox_3.isChecked() else ""
                )
            ),
            Next_Steps_in_Therapy="",
            Continue_Current_Protocol=(
                "Yes"
                if self.radioButton_5.isChecked()
                else "No" if self.radioButton_6.isChecked() else ""
            ),
            Adjust_Stimulation_Settings=(
                "Yes"
                if self.radioButton_7.isChecked()
                else "No" if self.radioButton_8.isChecked() else ""
            ),
            New_Settings="",
            Increase_Session_Frequency=(
                "Yes"
                if self.radioButton_9.isChecked()
                else "No" if self.radioButton_10.isChecked() else ""
            ),
            Introduce_New_Exercises=(
                "Yes"
                if self.radioButton_11.isChecked()
                else "No" if self.radioButton_12.isChecked() else ""
            ),
            Details="",
            experience_satisfying=(
                "Strongly Disagree"
                if self.radioButton_17.isChecked()
                else (
                    "Disagree"
                    if self.radioButton_18.isChecked()
                    else (
                        "Neutral"
                        if self.radioButton_19.isChecked()
                        else (
                            "Agree"
                            if self.radioButton_24.isChecked()
                            else (
                                "Strongly Agree"
                                if self.radioButton_25.isChecked()
                                else ""
                            )
                        )
                    )
                )
            ),
            comfortable_therapy=(
                "Strongly Disagree"
                if self.radioButton_26.isChecked()
                else (
                    "Disagree"
                    if self.radioButton_27.isChecked()
                    else (
                        "Neutral"
                        if self.radioButton_28.isChecked()
                        else (
                            "Agree"
                            if self.radioButton_29.isChecked()
                            else (
                                "Strongly Agree"
                                if self.radioButton_30.isChecked()
                                else ""
                            )
                        )
                    )
                )
            ),
            session_painful=(
                "Strongly Disagree"
                if self.radioButton_31.isChecked()
                else (
                    "Disagree"
                    if self.radioButton_32.isChecked()
                    else (
                        "Neutral"
                        if self.radioButton_33.isChecked()
                        else (
                            "Agree"
                            if self.radioButton_34.isChecked()
                            else (
                                "Strongly Agree"
                                if self.radioButton_35.isChecked()
                                else ""
                            )
                        )
                    )
                )
            ),
            hand_improved=(
                "Strongly Disagree"
                if self.radioButton_36.isChecked()
                else (
                    "Disagree"
                    if self.radioButton_37.isChecked()
                    else (
                        "Neutral"
                        if self.radioButton_38.isChecked()
                        else (
                            "Agree"
                            if self.radioButton_39.isChecked()
                            else (
                                "Strongly Agree"
                                if self.radioButton_40.isChecked()
                                else ""
                            )
                        )
                    )
                )
            ),
            Additional_Comments="",
            Quality_of_life_Improved=(
                "Yes"
                if self.radioButton_13.isChecked()
                else "No" if self.radioButton_14.isChecked() else ""
            ),
            Long_Term_Goals_Achieved=(
                "Yes"
                if self.radioButton_15.isChecked()
                else "No" if self.radioButton_16.isChecked() else ""
            ),
            Remaining_Challenges="",
            Continue_Home_Exercises=(
                "Yes"
                if self.radioButton_20.isChecked()
                else "No" if self.radioButton_21.isChecked() else ""
            ),
            Further_Clinical_Sessions_Needed=(
                "Yes"
                if self.radioButton_22.isChecked()
                else "No" if self.radioButton_23.isChecked() else ""
            ),
            Additional_Therapies_Suggested="",
        )

        try:
            newReport.generate_report(newReport.data["Name"])
            QMessageBox.information(
                self.centralwidget,
                "Report Added",
                "Report is added successfully!",
            )
        except Exception as e:
            QMessageBox.warning(self.centralwidget, "Error", "Invalid Data Provided")


import os
import pyrebase
from docx import Document
from docx2pdf import convert

TEMPLATE_PATH = "ReportTemplate.docx"
output_docx_path = "FilledReport.docx"


class Report:
    def __init__(
        self,
        Name,
        Patient_ID,
        Date_of_Birth,
        Gender,
        Hand_Dominance,
        Diagnosis,
        Referring_Clinician,
        Rehabilitation_Start_Date,
        Muscle_Weakness,
        Muscle_Paralysis,
        Muscle_Spasticity,
        Loss_of_Coordination,
        Tremors,
        Reduced_Range_of_Motion,
        Sensory_Loss,
        Pain,
        Hand_function_impairment,
        Muscle_Testing_Score,
        Number_of_Sessions,
        Discharge_Date,
        Medical_History,
        Waveform,
        Pulse_Frequency,
        Pulse_Intensity,
        Pulse_Width,
        Movement_Angle_cup,
        Accuracy_cup,
        Feedback_cup,
        is_adjustment_Required_cup,
        Additional_Notes_cup,
        Movement_Angle_pen,
        Accuracy_pen,
        Feedback_pen,
        is_adjustment_Required_pen,
        Additional_Notes_pen,
        Movement_Angle_key,
        Accuracy_key,
        Feedback_key,
        is_adjustment_Required_key,
        Additional_Notes_key,
        Movement_Angle_ball,
        Accuracy_ball,
        Feedback_ball,
        is_adjustment_Required_ball,
        Additional_Notes_ball,
        Movement_Angle_bottle,
        Accuracy_bottle,
        Feedback_bottle,
        is_adjustment_Required_bottle,
        Additional_Notes_bottle,
        Session_Date,
        Stimulation_Protocol,
        Target_Movements,
        Session_Duration,
        Performance_Feedback,
        Clinician_Notes,
        Improvements_Observed,
        Challenges_Noted,
        Side_effects,
        Next_Steps_in_Therapy,
        Continue_Current_Protocol,
        Adjust_Stimulation_Settings,
        New_Settings,
        Increase_Session_Frequency,
        Introduce_New_Exercises,
        Details,
        experience_satisfying,
        comfortable_therapy,
        session_painful,
        hand_improved,
        Additional_Comments,
        Quality_of_life_Improved,
        Long_Term_Goals_Achieved,
        Remaining_Challenges,
        Continue_Home_Exercises,
        Further_Clinical_Sessions_Needed,
        Additional_Therapies_Suggested,
    ):
        self.data = {
            "Name": Name,
            "Patient_ID": Patient_ID,
            "Date_of_Birth": Date_of_Birth,
            "Gender": Gender,
            "Hand_Dominance": Hand_Dominance,
            "Diagnosis": Diagnosis,
            "Referring_Clinician": Referring_Clinician,
            "Rehabilitation_Start_Date": Rehabilitation_Start_Date,
            "Muscle_Weakness": Muscle_Weakness,
            "Muscle_Paralysis": Muscle_Paralysis,
            "Muscle_Spasticity": Muscle_Spasticity,
            "Loss_of_Coordination": Loss_of_Coordination,
            "Tremors": Tremors,
            "Reduced_Range_of_Motion": Reduced_Range_of_Motion,
            "Sensory_Loss": Sensory_Loss,
            "Pain": Pain,
            "Hand_function_impairment": Hand_function_impairment,
            "Muscle_Testing_Score": Muscle_Testing_Score,
            "Number_of_Sessions": Number_of_Sessions,
            "Discharge_Date": Discharge_Date,
            "Medical_History": Medical_History,
            "Waveform": Waveform,
            "Pulse_Frequency": Pulse_Frequency,
            "Pulse_Intensity": Pulse_Intensity,
            "Pulse_Width": Pulse_Width,
            "Movement_Angle_cup": Movement_Angle_cup,
            "Accuracy_cup": Accuracy_cup,
            "Feedback_cup": Feedback_cup,
            "is_adjustment_Required_cup": is_adjustment_Required_cup,
            "Additional_Notes_cup": Additional_Notes_cup,
            "Movement_Angle_pen": Movement_Angle_pen,
            "Accuracy_pen": Accuracy_pen,
            "Feedback_pen": Feedback_pen,
            "is_adjustment_Required_pen": is_adjustment_Required_pen,
            "Additional_Notes_pen": Additional_Notes_pen,
            "Movement_Angle_key": Movement_Angle_key,
            "Accuracy_key": Accuracy_key,
            "Feedback_key": Feedback_key,
            "is_adjustment_Required_key": is_adjustment_Required_key,
            "Additional_Notes_key": Additional_Notes_key,
            "Movement_Angle_ball": Movement_Angle_ball,
            "Accuracy_ball": Accuracy_ball,
            "Feedback_ball": Feedback_ball,
            "is_adjustment_Required_ball": is_adjustment_Required_ball,
            "Additional_Notes_ball": Additional_Notes_ball,
            "Movement_Angle_bottle": Movement_Angle_bottle,
            "Accuracy_bottle": Accuracy_bottle,
            "Feedback_bottle": Feedback_bottle,
            "is_adjustment_Required_bottle": is_adjustment_Required_bottle,
            "Additional_Notes_bottle": Additional_Notes_bottle,
            "Session_Date": Session_Date,
            "Stimulation_Protocol": Stimulation_Protocol,
            "Target_Movements": Target_Movements,
            "Session_Duration": Session_Duration,
            "Performance_Feedback": Performance_Feedback,
            "Clinician_Notes": Clinician_Notes,
            "Improvements_Observed": Improvements_Observed,
            "Challenges_Noted": Challenges_Noted,
            "Side_effects": Side_effects,
            "Next_Steps_in_Therapy": Next_Steps_in_Therapy,
            "Continue_Current_Protocol": Continue_Current_Protocol,
            "Adjust_Stimulation_Settings": Adjust_Stimulation_Settings,
            "New_Settings": New_Settings,
            "Increase_Session_Frequency": Increase_Session_Frequency,
            "Introduce_New_Exercises": Introduce_New_Exercises,
            "Details": Details,
            "experience_satisfying": experience_satisfying,
            "comfortable_therapy": comfortable_therapy,
            "session_painful": session_painful,
            "hand_improved": hand_improved,
            "Additional_Comments": Additional_Comments,
            "Quality_of_life_Improved": Quality_of_life_Improved,
            "Long_Term_Goals_Achieved": Long_Term_Goals_Achieved,
            "Remaining_Challenges": Remaining_Challenges,
            "Continue_Home_Exercises": Continue_Home_Exercises,
            "Further_Clinical_Sessions_Needed": Further_Clinical_Sessions_Needed,
            "Additional_Therapies_Suggested": Additional_Therapies_Suggested,
        }

    def replace_placeholders(self, doc):
        for paragraph in doc.paragraphs:
            for key, value in self.to_dict().items():
                if f"{{{key}}}" in paragraph.text:
                    paragraph.text = paragraph.text.replace(f"{{{key}}}", str(value))

        for table in doc.tables:
            for row in table.rows:
                for cell in row.cells:
                    for key, value in self.to_dict().items():
                        if f"{{{key}}}" in cell.text:
                            cell.text = cell.text.replace(f"{{{key}}}", str(value))

    def create_filled_docx(self, output_docx_path):
        doc = Document(TEMPLATE_PATH)
        self.replace_placeholders(doc)
        doc.save(output_docx_path)

    def convert_to_pdf(self, output_docx_path, output_pdf_path):
        convert(output_docx_path, output_pdf_path)

    def upload_to_firebase_storage(self, file_path):
        config = {
            "apiKey": "AIzaSyBaf2PZ9lRnkpM952pBDlfGCxxEjcvU4Bk",
            "authDomain": "fes-controller.firebaseapp.com",
            "databaseURL": "https://fes-controller-default-rtdb.firebaseio.com",
            "projectId": "fes-controller",
            "storageBucket": "fes-controller.appspot.com",
            "messagingSenderId": "341771619246",
            "appId": "1:341771619246:web:29d7cc61c889b3228a163f",
        }

        # Initialize Firebase
        firebase = pyrebase.initialize_app(config)
        storage = firebase.storage()
        file_name = os.path.basename(file_path)
        storage.child(file_name).put(file_path)

    def generate_report(self, name):

        output_pdf_path = f"{name}_{date.today()}.pdf"
        self.create_filled_docx(output_docx_path)
        self.convert_to_pdf(output_docx_path, output_pdf_path)
        self.upload_to_firebase_storage(output_pdf_path)

        # Delete the DOCX and PDF files after uploading
        if os.path.exists(output_docx_path):
            os.remove(output_docx_path)
        if os.path.exists(output_pdf_path):
            os.remove(output_pdf_path)

    def to_dict(self):
        return self.data


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    PatientsPageMainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(PatientsPageMainWindow)
    PatientsPageMainWindow.show()
    sys.exit(app.exec_())
